### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by dkurt** [UNN-ITMM-Software/devtools-course-practice#225]
@pichugin-i, see report at https://app.codecov.io/gh/UNN-ITMM-Software/devtools-course-practice. Now module `ustiuzhanin_n_hashmap` has 68%

**Comment by dkurt** [comment]
@SHVlader, при открытиии PR бот сравнивает только внутри ветки с изменениями. Смотрите https://app.codecov.io/gh/UNN-ITMM-Software/devtools-course-practice/blob/main/modules/ustiuzhanin_n_hashmap/include/hashmap.h

**Comment by SHVlader** [comment]
@dkurt были добавлены тесты, но на сайте они почему-то не обновляются, взгляните пожалуйста
https://github.com/UNN-ITMM-Software/devtools-course-practice/pull/252

**Comment by dkurt** [comment]
I have some guess that methods which remain uncovered are all inside `ASSERT_NO_THROW` or `ASSERT_ANY_THROW` macros. So, let's try check something more complex:
```cpp
    Hashmap<string, int> h;
    h.insert("str", 1);
    h.insert("string", 11);
    Hashmap<string, int> hh;
    hh = h;
   
    ASSERT_EQ(h[0], hh[0]);
    ASSERT_EQ(h[1], hh[1]);
```

**Comment by SHVlader** [comment]
Я обычно не считаю их, тестами ведь их невозможно покрыть
