### ISSUE TITLE
Персональное задание: Мухин Иван 3821Б1ПМоп3

### ISSUE THREAD

**Issue by dkurt** [UNN-ITMM-Software/devtools-course-practice#256]
@ismukhin

Необходимо выполнить любую задачу в одном из популярных open source проектов. Это может быть как задача по коду, так и по документации. Требуется предоставить ссылку на открытый пулл реквест. Если полезность вклада в выбранный проект не вызывает вопросов - метка "delayed" будет снята с вашей лабораторной работы.

**Comment by ismukhin** [comment]
https://github.com/itlab-vision/dl-benchmark/pull/507
https://github.com/itlab-vision/dl-benchmark/pull/494
https://github.com/itlab-vision/dl-benchmark/pull/482
https://github.com/itlab-vision/dl-benchmark/pull/481
https://github.com/itlab-vision/dl-benchmark/pull/478

**Comment by ismukhin** [comment]
https://github.com/apache/tvm/issues?page=4&q=is%3Aissue+is%3Aopen
Не задача, но оставлял issue здесь

**Comment by dkurt** [comment]
@ismukhin, принимаем, спасибо!
