### ISSUE TITLE
Персональное задание: Бодров Даниил 3821Б1ФИ1

### ISSUE THREAD

**Issue by dkurt** [UNN-ITMM-Software/devtools-course-practice#259]
@overinvest,

Необходимо выполнить любую задачу в одном из популярных open source проектов. Это может быть как задача по коду, так и по документации. Требуется предоставить ссылку на открытый пулл реквест. Если полезность вклада в выбранный проект не вызывает вопросов - метка "delayed" будет снята с вашей лабораторной работы.

**Comment by overinvest** [comment]
https://github.com/telegramdesktop/tdesktop/pull/27774

**Comment by overinvest** [comment]
Так же обновил алгоритм в одном популярном репе

https://github.com/TheAlgorithms/C-Plus-Plus/pull/2691

@dkurt

**Comment by dkurt** [comment]
@overinvest, принято. Пожалуйста доведите по возможности эти PR до мерджа, учитывая комментарии от контрибьюторов.
