### ISSUE TITLE
Персональное задание: Соколова Дарья 3821Б1ПР1

### ISSUE THREAD

**Issue by dkurt** [UNN-ITMM-Software/devtools-course-practice#261]
@SokolovaDaria

Необходимо выполнить любую задачу в одном из популярных open source проектов. Это может быть как задача по коду, так и по документации. Требуется предоставить ссылку на открытый пулл реквест. Если полезность вклада в выбранный проект не вызывает вопросов - метка "delayed" будет снята с вашей лабораторной работы.

**Comment by SokolovaDaria** [comment]
https://github.com/BitCodersNN/unn-mobile/pull/303
https://github.com/BitCodersNN/unn-mobile/pull/347 

@dkurt

**Comment by dkurt** [comment]
Принято
