### ISSUE TITLE
Ошибка в Pull Requests!!!

### ISSUE THREAD

**Issue by SmirnovLM** [UNN-ITMM-Software/devtools-course-practice#298]
Проверка Linux/ Build and Test (CodeCheck) выдает следующую ошибку на этапе Run tests:

Error(s) when building project
MakeCommand:/usr/local/bin/cmake -P /home/runner/work/devtools-course-practice/devtools-course-practice/dashboard/build/ctest_ext_build.cmake
Testing passed OK
   1 Compiler errors
   0 Compiler warnings
Error: Process completed with exit code 255.

НИКАК не понятно как ее решить и с чем она связана, хотя при всем при этом, при прохождении по файлам проверкой cpplint ошибок не вылазит, все в пределах нормы

**Comment by dkurt** [comment]
Добавьте ссылку на PR

**Comment by SmirnovLM** [comment]
@dkurt
https://github.com/UNN-ITMM-Software/devtools-course-practice/pull/297

**Comment by dkurt** [comment]
@SmirnovLM:

```
The following tests FAILED:
	 72 - kirillov_m_quadratic_solution_run_quadratic_solver_real_roots (Failed)
	 74 - kirillov_m_quadratic_solution_run_quadratic_solver_complex_roots (Failed)
```
```
72/179 Test  #72: kirillov_m_quadratic_solution_run_quadratic_solver_real_roots ...........***Failed  Required regular expression not found. Regex=[Real Roots: 1 2
```
```
 74/179 Test  #74: kirillov_m_quadratic_solution_run_quadratic_solver_complex_roots ........***Failed  Required regular expression not found. Regex=[Complex Roots: -1\+0i 2.23607\+0i -2.23607\+0i
```
