### ISSUE TITLE
Доп. задание. Лаб. 3. Тушенцова Карина, 3821Б1ПР1

### ISSUE THREAD

**Issue by karrin0chka** [UNN-ITMM-Software/devtools-course-practice#359]
Есть ли возможность убрать пометку delayed, так как разработчик выбранного мною модуля выложил реализацию только за 5 дней до конца дедлайна сдачи 3 лабораторной?

**Comment by dkurt** [comment]
Скиньте ссылку на pull request

**Comment by karrin0chka** [comment]
> Скиньте ссылку на запрос на включение

https://github.com/UNN-ITMM-Software/devtools-course-practice/pull/357

**Comment by dkurt** [comment]
Принято, метка удалена
