### ISSUE TITLE
Шемякина - Дополнительное задание, 3821Б1ПМоп3

### ISSUE THREAD

**Issue by alesyacurtis** [UNN-ITMM-Software/devtools-course-practice#382]

**Comment by Kuznetsov-Artyom** [comment]
@alesyacurtis Необходимо выполнить любую задачу в одном из популярных open source проектов. Это может быть как задача по коду, так и по документации. Требуется предоставить ссылку на открытый пулл реквест. Если полезность вклада в выбранный проект не вызывает вопросов - метка "delayed" будет снята с вашей лабораторной работы.
