### ISSUE TITLE
Персональное задание: Новостроев Иван. Группа 3821Б1ПР2

### ISSUE THREAD

**Issue by FirewallGR** [UNN-ITMM-Software/devtools-course-practice#386]
@GERONlMO  Необходимо выполнить любую задачу в одном из популярных open source проектов. Это может быть как задача по коду, так и по документации. Требуется предоставить ссылку на открытый пулл реквест. Если полезность вклада в выбранный проект не вызывает вопросов - метка "delayed" будет снята с вашей лабораторной работы.

**Comment by GERONlMO** [comment]
https://github.com/MaximFLUNN/Pocket_Portal/pull/2
