### ISSUE TITLE
Разночтения в инструкции по выполнению

### ISSUE THREAD

**Issue by alexbatashev** [UNN-ITMM-Software/devtools-course-practice#44]
https://github.com/UNN-ITMM-Software/devtools-course-practice/blame/master/lab-guide/lab-1-setup.md#L54 -- добавить не менее 5 тестов

https://github.com/UNN-ITMM-Software/devtools-course-practice/blame/master/lab-guide/lab-1-setup.md#L161 -- не менее 3 тестов

**Comment by kirill-korniakov** [comment]
Думаю достаточно будет и 3, можете прислать PR с правками.
