### ISSUE TITLE
Отсутствие отметки в таблице с результатами

### ISSUE THREAD

**Issue by Namxobick** [UNN-ITMM-Software/devtools-course-practice#84]
Моя л.р. 1 находится в main ветке, но в таблице нет отметки об этом.
<img width="397" alt="image" src="https://github.com/UNN-ITMM-Software/devtools-course-practice/assets/100288192/1a6071a3-6899-4eae-8b4c-c77bb3577751">
<img width="936" alt="image" src="https://github.com/UNN-ITMM-Software/devtools-course-practice/assets/100288192/f18e6331-57da-424b-b12f-3b2ebf1cb0a7">

**Comment by dkurt** [comment]
В названии PR не было числа, по которому бот мог бы определить номер лабы. Выставил вручную. https://github.com/UNN-ITMM-Software/devtools-course-practice/pull/37

**Comment by dkurt** [comment]
![image](https://github.com/UNN-ITMM-Software/devtools-course-practice/assets/25801568/dabc7ac6-56aa-4973-907d-8c7facb34bf5)
